services:
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_fpm
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_products
      MYSQL_USER: app_usr_dp
      MYSQL_PASSWORD: app_db_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3336:3306
    networks:
      - app-network

  nginx:
    image: nginx:1.19
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge